version: 2
sources:
  - name: source
    database: '{{target.catalog}}'
    schema: source
    tables:
      - name: dim_customer
      - name: dim_date
      - name: dim_product
      - name: dim_store
      - name: fact_returns
      - name: fact_sales

